spring.application.name=conversational-layer
spring.datasource.url=jdbc:postgresql://localhost:5432/aistetic_conversational
spring.datasource.username=shrisakthi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=dev

whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.business-account-id=${WHATSAPP_BUSINESS_ACCOUNT_ID}
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN}