spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/aistetic_conversational}
spring.datasource.username=${DB_USERNAME:shrisakthi}
spring.datasource.password=${DB_PASSWORD:}

# AI
AI_API_KEY=${AI_API_KEY:}

# WhatsApp